Create 1
vu-cs3892-21s/Group7 pull request #5
Opened 2021-03-12 05:54 UTC by samspeer

Created the game page and updated formatting

2021-03-12 19:19 UTC, timothycobrien requested changes

2021-03-12 19:19 UTC, timothycobrien commented on client/src/components/create.tsx
> +const gameModes: { name: string, description: string, icon: any }[] = [
Make this type line up with the possible types of icon using a union type or interface

2021-03-12 19:19 UTC, timothycobrien commented on client/src/index.tsx
> +  font-family: Revalia;
Rather use a different font, and add backup font possibly

2021-03-13 00:37 UTC, timothycobrien commented on client/src/components/create.tsx
> +const gameModes: { name: string, description: string, icon: any }[] = [
`icon` should not have `any` type

2021-03-16 15:47 UTC, samspeer commented on client/src/components/create.tsx
> +const gameModes: { name: string, description: string, icon: any }[] = [
I am not quite sure how to type the fact it is a component?

2021-03-16 15:54 UTC, timothycobrien requested changes

2021-03-16 15:54 UTC, timothycobrien commented on client/src/components/create.tsx
> +const gameModes: { name: string, description: string, icon: any }[] = [
It's either a PersonIcon or a GroupIcon right, so type it as the union of these two types so it can be either

2021-03-16 16:24 UTC, timothycobrien approved these changes

2021-03-16 16:24 UTC, merged